---
title: "HotSpotTracker"
author: Patrick Reza Schnurbusch 
date: '`r paste("Updated: ", format(Sys.time(), "%Y-%m-%d"))`'
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    theme: paper
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)

library(geojsonio)
library(leaflet)
library(leaflet.extras)
library(leaflet.providers)
library(sf)

library(dplyr)
library(tidyr)

library(lubridate)

#read polygon data 
# loc = "https://opendata.arcgis.com/datasets/d8fba69152e4408dabfe70e85a2688d2_44.geojson"
# PHU_boundaries <- geojsonio::geojson_read(loc, what = "sp")
# 
# PHU_boundaries_sf <- sf::st_as_sf(PHU_boundaries)


library("rgdal")
#write polygon data
# st_write(PHU_boundaries_sf, "./spatial files/PHU_Boundaries.geojson")



#read file in 
PHU_boundaries_sf <-  geojsonio::geojson_read("./spatial files/PHU_Boundaries.geojson" , what = "sp")
PHU_boundaries_sf <- sf::st_as_sf(PHU_boundaries_sf)

```

GIS
===================================== 
Row {.tabset .tabset-fade}
-------------------------------------

```{r}
#download casestatus data 

library(data.table)

url <- "https://data.ontario.ca/dataset/f4112442-bdc8-45d2-be3c-12efae72fb27/resource/455fd63b-603d-4608-8216-7d8647f43350/download/conposcovidloc.csv"

CaseStatus <- data.table::fread(input = url, encoding = "UTF-8")
```


```{r}
CaseStatus$Case_Reported_Date <- as.Date(CaseStatus$Case_Reported_Date)

PHU_csums <- data.frame(CaseStatus %>% 
  dplyr::group_by(Reporting_PHU) %>% 
  dplyr::count(name = "csum") %>% 
  dplyr::arrange(Reporting_PHU) %>% 
  dplyr::mutate(Reporting_PHU = trimws(Reporting_PHU, which = "both"))
)

 #fixing 5 rows that the PHU name is not verbatim as in the shp boundary file 
PHU_csums$Reporting_PHU <- ifelse(PHU_csums$Reporting_PHU == "Huron Perth District Health Unit", "Huron Perth Health Unit", 
                               ifelse(PHU_csums$Reporting_PHU == "Kingston, Frontenac and Lennox & Addington Public Health", "Kingston, Frontenac and Lennox and Addington Health Unit",
                                      ifelse(PHU_csums$Reporting_PHU == "Sudbury & District Health Unit", "Sudbury and District Health Unit", 
                                             ifelse(PHU_csums$Reporting_PHU == "Wellington-Dufferin-Guelph Public Health", "Wellington-Dufferin-Guelph Health Unit", 
                                                    ifelse(PHU_csums$Reporting_PHU == "York Region Public Health Services", "York Region Public Health", PHU_csums$Reporting_PHU)
                                             )
                                      )
                               )
)
```


### <b> Cumulative per PHU </b> 
```{r}
csum_map <- merge(PHU_boundaries_sf, PHU_csums, by.x = "PHU_NAME_ENG", by.y = "Reporting_PHU" )
 
pal <- colorNumeric("RdBu", domain = csum_map$csum, reverse = T)
 

leaflet() %>% 
   setView(lat = 51.2538, lng = -85.3232, zoom = 5.25) %>%
   addProviderTiles(providers$CartoDB.Positron) %>% 
   addPolygons(data  = csum_map,
               fillColor = ~pal(csum), 
               weight = 2, 
               opacity = 1, 
               color = "white", 
               dashArray = 3, 
               fillOpacity = 0.25, 
               
               highlightOptions = highlightOptions(
                 weight = 4, 
                 color = "yellow", 
                 fillOpacity = 0.5, 
                 bringToFront = T), 
               
               labelOptions = labelOptions(
                 style = list("font-weight" = "normal", padding = "3px 8px"),
                 textsize = "15px",
                 direction = "auto")
               ) %>%
   addFullscreenControl() %>% 
   addResetMapButton() %>% 
   
   ## adding locate me button 
   addEasyButton(easyButton(
     icon="fa-crosshairs", title="Locate Me",
     onClick=JS("function(btn, map){ map.locate({setView: true});}"))) %>% 

   addLegend("bottomright", pal = pal, values = csum_map$csum, 
             title = "Current Cumulative Cases", 
             opacity = 0.5)
```

### <b> Cartogram </b> 


GeoStatistics
===================================== 
Row {.tabset .tabset-fade}
-------------------------------------

### <b> Spatial Autocorrelation </b> 
### <b> Confidence Intervals </b> 

